language: nodejs

services:
  - docker
branches:
  only:
  - master
script:
  - make test-and-copy-dist

before_deploy:
  - cd dist
deploy:
  provider: npm
  email: dev@apiumhub.com
  api_key:
    secure: $ADH_NPM_TOKEN
