language: nodejs

services:
- docker
branches:
  only:
  - master
before_script:
  - npm install -g typescript
  - npm run tsc
script:
  - make test
after_success:
  - npm pack
deploy:
  provider: npm
  email: dev@apiumhub.com
  api_key:
    secure: $ADH_NPM_TOKEN