language: nodejs

services:
- docker
branches:
  only:
  - master
script:
  - make test
  - npm run tsc
after_success:
  - npm pack
deploy:
  provider: npm
  email: dev@apiumhub.com
  api_key:
    secure: $ADH_NPM_TOKEN